export enum Permission {
    READ_CLASSROOM = 'READ_CLASSROOM',
    WRITE_CLASSROOM = 'WRITE_CLASSROOM',
    READ_CLASSROOM_MEMBER = 'READ_CLASSROOM_MEMBER',
    WRITE_CLASSROOM_MEMBER = 'WRITE_CLASSROOM_MEMBER',
    READ_INVITATION = 'READ_INVITATION',
    WRITE_INVITATION = 'WRITE_INVITATION',
}
