export type SystemProp = AppSystemProp | SharedSystemProp

export enum AppSystemProp {
    DB_TYPE = 'DB_TYPE',
    ENCRYPTION_KEY = 'ENCRYPTION_KEY',
    JWT_SECRET = 'JWT_SECRET',
    MAX_FILE_SIZE_MB = 'MAX_FILE_SIZE_MB',

    FIREBASE_HASH_PARAMETERS = 'FIREBASE_HASH_PARAMETERS',
    LICENSE_KEY = 'LICENSE_KEY',
    POSTGRES_DATABASE = 'POSTGRES_DATABASE',
    POSTGRES_HOST = 'POSTGRES_HOST',
    POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
    POSTGRES_PORT = 'POSTGRES_PORT',
    POSTGRES_SSL_CA = 'POSTGRES_SSL_CA',
    POSTGRES_URL = 'POSTGRES_URL',
    POSTGRES_USERNAME = 'POSTGRES_USERNAME',
    POSTGRES_USE_SSL = 'POSTGRES_USE_SSL',
    EDITION = 'EDITION',
    API_RATE_LIMIT_AUTHN_MAX = 'API_RATE_LIMIT_AUTHN_MAX',
    API_RATE_LIMIT_AUTHN_WINDOW = 'API_RATE_LIMIT_AUTHN_WINDOW',
    API_RATE_LIMIT_AUTHN_ENABLED = 'API_RATE_LIMIT_AUTHN_ENABLED',
    SMTP_SENDER_NAME = 'SMTP_SENDER_NAME',
    SMTP_SENDER_EMAIL = 'SMTP_SENDER_EMAIL',
    SMTP_HOST = 'SMTP_HOST',
    SMTP_PORT = 'SMTP_PORT',
    SMTP_USERNAME = 'SMTP_USERNAME',
    SMTP_PASSWORD = 'SMTP_PASSWORD',
    SHOW_PLATFORM_DEMO = 'SHOW_PLATFORM_DEMO',
}

export enum SharedSystemProp  {
    LOG_LEVEL = 'LOG_LEVEL',
    LOG_PRETTY = 'LOG_PRETTY',
    ENVIRONMENT = 'ENVIRONMENT',
    FRONTEND_URL = 'FRONTEND_URL',
    CONTAINER_TYPE = 'CONTAINER_TYPE',
    EMAIL_AUTH_ENABLED = 'EMAIL_AUTH_ENABLED',
    // Cloud Only & Enterprise Only
    SENTRY_DSN = 'SENTRY_DSN',
    LOKI_PASSWORD = 'LOKI_PASSWORD',
    LOKI_URL = 'LOKI_URL',
    LOKI_USERNAME = 'LOKI_USERNAME',

}