export * from './lib/common'
export * from './lib/flag/flag'
export * from './lib/authentication/dto/authentication-response'
export * from './lib/authentication/dto/sign-up-request'
export * from './lib/authentication/dto/sign-in-request'
export * from './lib/authentication/model/principal-type'
export * from './lib/authentication/model/principal'
export * from './lib/common/seek-page'
export * from './lib/common/id-generator'
export * from './lib/common/base-model'
export * from './lib/classroom'
export * from './lib/platform'
export * from './lib/authentication'
export * from './lib/otp'
export * from './lib/user'
export * from './lib/roles'
export * from './lib/classroom-member'
export * from './lib/classroom-role'
export * from './lib/invitations'
export * from './lib/audit-events'
// Look at https://github.com/sinclairzx81/typebox/issues/350
import { TypeSystemPolicy } from '@sinclair/typebox/system'
TypeSystemPolicy.ExactOptionalPropertyTypes = false
